#!/bin/bash

# chkconfig: 345 80 20
# description: A Private NPM Server Proxy
# processname: kappa
# pidfile: /var/run/kappa.pid
# logfile: /var/log/kappa.log

NAME=kappa
APP_DIR=/x/web/kappa
APP_MAIN=index.js
PORT=8001
RETVAL=0

user=$NAME
node=/x/home/ertoth/node-v0.10.7/out/Release/node # FIXME
opts=$APP_DIR/$APP_MAIN
pidfile=/var/run/$NAME.pid
logfile=/var/log/$NAME.log
lockfile=/var/lock/kappa


# Source function library
. /etc/init.d/functions


start() {
       [ -x $node ] || exit 5
       echo "Starting $NAME"

       if [ -s ${pidfile} ]; then
           RETVAL=1
           echo "$NAME is already running"
           echo_warning
       else
           runuser -s /bin/bash - $user -c "KAPPA_PORT=${PORT} nohup ${node} ${opts}" >> ${logfile} 2>&1 &

           RETVAL=$?
           [ $RETVAL = 0 ] && touch ${lockfile}

           PID=$!
           if [ -z $PID ]; then
               echo_failure
           else
               echo
               echo $PID > ${pidfile}
               echo_success
           fi
       fi

       return $RETVAL
}

stop() {
    echo "Shutting down $NAME"
    killproc -p ${pidfile} ${node}
    RETVAL=$?
    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
    return $RETVAL
}

case "$1" in
  start)
    $1
    ;;
  stop)
    $1
    ;;
  status)
    status -p ${pidfile}
    ;;
  *)
    echo "Usage:  {start|stop|status}"
    exit 1
    ;;
esac
exit $?