#!/bin/bash

# chkconfig: 345 80 20
# description: A Private NPM Server Proxy
# processname: turnip
# pidfile: /var/run/turnip.pid
# logfile: /var/log/turnip.log

NAME=turnip
APP_DIR=/x/web/turnip
APP_MAIN=index.js
PORT=8001

user=$NAME
node=/x/home/ertoth/node-v0.10.7/out/Release/node # FIXME
opts=$APP_DIR/$APP_MAIN
pidfile=/var/run/$NAME.pid
logfile=/var/log/$NAME.log

# Source function library
. /etc/init.d/functions


start() {
    #[ -x $node ] || exit 5
    echo "Starting $NAME"

    # Create the log and pid files, making sure that
    # the target use has access to them
    touch $logfile
    chown $user $logfile

    touch $pidfile
    chown $user $pidfile

    daemon --user $user --pidfile $pidfile --check $node  "TURNIP_PORT=$PORT $node $opts >> $logfile 2>&1 &" && echo_success || echo_failure

    retval=$?
    return $retval
}

stop() {
    echo "Shutting down $NAME"
    killproc $node
#    [ $retval -eq 0 ] && rm -f $lockfile
    retval=$?
    return $retval
}

case "$1" in
  start)
    $1
    ;;
  stop)
    $1
    ;;
  status)
    status -p ${pidfile}
    ;;
  *)
    echo "Usage:  {start|stop|status}"
    exit 1
    ;;
esac
exit $?